services:
  mysql:
    container_name: mysql-bms
    image: mysql:8.0.32
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: book_management_system
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3309:3306" # Map container's 3306 to host's 3300
    networks:
      - spring-demo
    restart: unless-stopped

  mail-dev:
    container_name: mail-dev-bms
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"

networks:
  spring-demo:
    driver: bridge

volumes:
  mysql-data:
    driver: local
