services:
  mysql:
    container_name: mysql-bms
    image: mysql:8.0.32
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: book_management_system
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - spring-demo
    restart: unless-stopped

  mail-dev:
    container_name: mail-dev-bms
    image: maildev/maldev
    ports:
      - 1080:1080
      - 1025:1025


networks:
  spring-demo:
    driver: bridge

volumes:
  mysql-data:
    driver: local