spring:
  datasource:
    url: jdbc:mysql://localhost:3300/book_management_system?createDatabaseIfNotExist=true
    username: username
    password: username
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
      database: mysql

  mail:
    host: localhost
    port: 1025
    username: ruwan
    password: 123456
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000


